# Generated by Django 4.1.7 on 2023-02-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_location_skill"),
    ]

    operations = []
